[env:m5stack-fire]
platform = espressif32
board = m5stack-fire
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DLV_CONF_SKIP
    -DLV_COLOR_DEPTH=16
    -DLV_USE_LOG=0
    -DLV_USE_BAR=1
    -DLV_USE_LABEL=1
    -DLV_USE_ARC=1
    -DLV_USE_BTN=1
    -DLV_USE_LINE=1
    -DLV_USE_OBJ=1
    -DLV_USE_IMG=1
    -DLV_USE_IMAGE=1
    -DLV_USE_ANIMIMG=0
    -DLV_TICK_CUSTOM=1
    -DLV_USE_SNAPSHOT=1

lib_deps =
    m5stack/M5Unified@^0.2.7
    m5stack/M5GFX@^0.2.7
    bblanchon/ArduinoJson@^7.0.0
